# Generated by Django 2.2.3 on 2019-10-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendente', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
