# Generated by Django 2.2.3 on 2019-10-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.BooleanField(default=True),
        ),
    ]
