# Generated by Django 2.2.3 on 2019-10-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_auto_20191020_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cidade',
            new_name='data_aniversario',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
    ]
