# Generated by Django 2.2.3 on 2019-10-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_auto_20191024_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data_aniversario',
            new_name='data_nascimento',
        ),
    ]
