# Generated by Django 2.2.3 on 2019-10-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_auto_20191024_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data_nascimento',
            new_name='nascimento',
        ),
    ]
