# Generated by Django 2.2.3 on 2019-10-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0005_auto_20191024_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nascimento',
            new_name='dt_nascimento',
        ),
    ]
