# Generated by Django 2.2.1 on 2019-11-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_venda',
            field=models.FloatField(default=0),
        ),
    ]
