# Generated by Django 2.2.3 on 2019-10-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto_pedido',
            name='preco_venda',
            field=models.FloatField(default=0),
        ),
    ]
