# Generated by Django 2.2.1 on 2019-11-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0002_produto_pedido_preco_venda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto_pedido',
            old_name='preco_venda',
            new_name='desconto',
        ),
    ]
